### ISSUE TITLE
Yass main window doesn't open at all

### ISSUE THREAD

**Issue by gregoy1** [SarutaSan72/Yass#129]
I've been having a blast using Yass lately to make songs for the community, but starting with Yass version 2.4.1, the main window doesn't appear at all. If I run the main .exe, the splash screen shows, but it disappears shortly after and nothing happens. If I run it again, but while having Task Manager open, I can see that Yass is loaded, but it disappears quickly. This is happening also with the latest version, 2.4.2. The working version for me is 2.4.0, wich opens normally. To further investigate, I tried opening both the .exe and the jar executable version via PowerShell, and this the error that I'm getting:
`PS E:\Program Files (x86)\Yass Along> java -jar yass.exe
AudioSystem and MidiSystem Sequencer found.
Init...
Loading properties: C:\Users\grego\.yass\user.xml
Mics: Driver de captura de som primário|Microfone (Realtek High Definit|Microfone (3- WO Mic Device)|Mixagem estéreo (Realtek High D|Microfone (2- WO Mic Device)
Selecting Mic:
Setting Language: pt
Exception in thread "AWT-EventQueue-0" java.util.MissingResourceException: Can't find bundle for base name yass.resources.i18.yass, locale pt
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
        at java.util.ResourceBundle.getBundleImpl(Unknown Source)
        at java.util.ResourceBundle.getBundle(Unknown Source)
        at yass.I18.setLanguage(I18.java:87)
        at yass.YassMain.initLanguage(YassMain.java:304)
        at yass.YassMain.init(YassMain.java:209)
        at yass.YassMain.lambda$initLater$0(YassMain.java:73)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

 I'm reporting this as a error/bug, because other people may be facing this same issue. 
Just as a information, I'm on Windows 10, 21H2; Thanks in advance.

**Comment by SarutaSan72** [comment]
Please delete the folder `C:\Users\grego\.yass` and try again.

**Comment by LenaWil** [comment]
I get the same error, after deleting .yass on macOS.

**Comment by SarutaSan72** [comment]
Somehow the default language is "pt" and the language loader fails. I've added a fallback to English.
Please try if this fixes your problem:
https://yass-along.com/data/downloads/yass-installer-2.4.3.exe
https://yass-along.com/data/downloads/yass-2.4.3.jar

These were my changes: https://github.com/SarutaSan72/Yass/pull/130/files

**Comment by gregoy1** [comment]
Thanks for the fast help. After installing your fixed Yass, now it opens normally... Can this fix be propagated to the stable release? Because there may be people with this same problem and they can't work on their songs... Will try to work on a song to see if anything wrong happens, and will let you know of that. Thanks...

**Comment by SarutaSan72** [comment]
Thanks, too. Done
