### ISSUE TITLE
Not working with Java 9

### ISSUE THREAD

**Issue by SarutaSan72** [SarutaSan72/Yass#14]
Library group icons and song info are missing.
Editor stalls when playing a "click".

Exception on loading:
```
java.lang.NullPointerException
        at yass.YassSynth.loadWav(YassSynth.java:240)
        at yass.YassPlayer$1.run(YassPlayer.java:131)
java.lang.NullPointerException
        at java.desktop/javax.swing.ImageIcon.<init>(Unknown Source)
        at yass.YassGroups.<init>(YassGroups.java:135)
        at yass.YassMain.createSongListPanel(YassMain.java:544)
        at yass.YassMain.init(YassMain.java:243)
        at yass.YassMain$1.run(YassMain.java:79)
```
Java 9 restricts resource loading. They must be contained in the same "module".

**Comment by SarutaSan72** [comment]
Done. Resources moved to yass package, Launch4J updated to newer version that supports Java 9.
Tested with JRE 1.8 and JRE 9, also working when requiring min-version=9.0.0.0. **Attention: Oracle changed version scheme to 9.0.0.0.**
